security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        doctrine:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            provider: doctrine
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: login
            guard:
                authenticators:
                    - AppBundle\Security\FormAuthenticator

    access_control:
        - { path: ^/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users,  roles: ROLE_ADMIN }
        - { path: ^/,       roles: [ROLE_ADMIN, ROLE_USER] }
